# Generated by Django 2.1.8 on 2019-05-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpressposts',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='wordpress_plugin_wordpressposts', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='wordpressposts',
            name='date_format',
            field=models.CharField(default='D d M Y', max_length=50),
        ),
    ]
